package com.shaunmitchell.messagingapp.utility;

public class CannedAnswers
{
	public final static String[] answers = new String[]
	{
			"Moral indignation is jealousy with a halo.- H. G. Wells (1866-1946)",
			"Glory is fleeting, but obscurity is forever.",
			"The fundamental cause of trouble in the world is that the stupid are cocksure while the intelligent are full of doubt.",
			"Victory goes to the player who makes the next-to-last mistake.",
			"Don't be so humble - you are not that great.",
			"His ignorance is encyclopedic",
			"If a man does his best, what else is there?",
			"Political correctness is tyranny with manners.",
			"You can avoid reality, but you cannot avoid the consequences of avoiding reality.",
			"When one person suffers from a delusion it is called insanity; when many people suffer from a delusion it is called religion.",
			"Sex and religion are closer to each other than either might prefer.",
			"I can write better than anybody who can write faster, and I can write faster than anybody who can write better.",
			"People demand freedom of speech to make up for the freedom of thought which they avoid.",
			"Give me chastity and continence, but not yet.",
			"Not everything that can be counted counts, and not everything that counts can be counted.",
			"Only two things are infinite, the universe and human stupidity, and I'm not sure about the former.",
			"A lie gets halfway around the world before the truth has a chance to get its pants on.",
			"You may not be interested in war, but war is interested in you.",
			"I do not feel obliged to believe that the same God who has endowed us with sense, reason, and intellect has intended us to forgo their use.",
			"We are all atheists about most of the gods humanity has ever believed in. Some of us just go one god further.",
			"The artist is nothing without the gift, but the gift is nothing without work.",
			"This book fills a much-needed gap.",
			"The full use of your powers along lines of excellence.",
			"I'm living so far beyond my income that we may almost be said to be living apart.",
			"Give me a museum and I'll fill it.",
			"Assassins!",
			"I'll moider da bum.",
			"In theory, there is no difference between theory and practice. But in practice, there is.",
			"I find that the harder I work, the more luck I seem to have.",
			"Each problem that I solved became a rule which served afterwards to solve other problems.",
			"Discours de la Methode",
			"In the End, we will remember not the words of our enemies, but the silence of our friends.",
			"Whether you think that you can, or that you can't, you are usually right.",
			"Do, or do not. There is no 'try'.",
			"The only way to get rid of a temptation is to yield to it.",
			"Don't stay in bed, unless you can make money in bed.",
			"I don't know why we are here, but I'm pretty sure that it is not in order to enjoy ourselves.",
			"There are no facts, only interpretations.",
			"Nothing in the world is more dangerous than sincere ignorance and conscientious stupidity.",
			"The use of COBOL cripples the mind; its teaching should, therefore, be regarded as a criminal offense.",
			"C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do, it blows away your whole leg.",
			"A mathematician is a device for turning coffee into theorems.",
			"Problems worthy of attack prove their worth by fighting back.",
			"Try to learn something about everything and everything about something.",
			"Dancing is silent poetry.",
			"The only difference between me and a madman is that I'm not mad.",
			"If you can't get rid of the skeleton in your closet, you'd best teach it to dance.",
			"But at my back I always hear Time's winged chariot hurrying near.",
			"Good people do not need laws to tell them to act responsibly, while bad people will find a way around the laws.",
			"The power of accurate observation is frequently called cynicism by those who don't have it.",
			"Whenever I climb I am followed by a dog called 'Ego'.",
			"Everybody pities the weak; jealousy you have to earn.",
			"Against stupidity, the gods themselves contend in vain.",
			"We have art to save ourselves from the truth.",
			"Never interrupt your enemy when he is making a mistake.",
			"I think 'Hail to the Chief' has a nice ring to it.",
			"I have nothing to declare except my genius.",
			"Human history becomes more and more a race between education and catastrophe.",
			"Talent does what it can; genius does what it must.",
			"The difference between 'involvement' and 'commitment' is like an eggs-and-ham breakfast: the chicken was 'involved' - the pig was 'committed'.",
			"Women might be able to fake orgasms. But men can fake a whole relationship.",
			"If you are going through hell, keep going.",
			"Life isn't about waiting for the storm to pass; it's about learning to dance in the rain.",
			"He who has a 'why' to live, can bear with almost any 'how'.",
			"Many wealthy people are little more than janitors of their possessions.",
			"I'm all in favor of keeping dangerous weapons out of the hands of fools. Let's start with typewriters.",
			"Some cause happiness wherever they go; others, whenever they go.",
			"God is a comedian playing to an audience too afraid to laugh.",
			"He is one of those people who would be enormously improved by death.", };
}